apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ax-sentinel-default
  labels:
    {{- include "ax-sentinel.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: ax-sentinel
  policyTypes: ["Ingress", "Egress"]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 80
        {{- if .Values.redis.enabled }}
        - protocol: TCP
          port: 6379
        {{- end }}
        {{- if .Values.keycloak.enabled }}
        - protocol: TCP
          port: 5432
        {{- end }}
  egress:
    - {}
